name: Build Flutter APK

on:
    push:
      branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Android Structure
        run: |
          flutter create . --org com.khateeb.pos --project-name khateeb_pos --platforms=android

      - name: Restore Custom main.dart
        run: |
          # سيتم التأكد من بقاء ملف الـ main.dart الخاص بك
          ls -la lib/

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
